<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.131" timestamp="2025-10-05T22:45:10.470744+05:30" hostname="DESKTOP-5KEU3I8"><testcase classname="xmlreport_test" name="test_assert_one" time="0.002" /><testcase classname="xmlreport_test" name="test_assert_two" time="0.002" /><testcase classname="xmlreport_test" name="test_assert_three" time="0.001" /><testcase classname="xmlreport_test" name="test_assert_four" time="0.001"><failure message="AssertionError: A is not equal to B&#10;assert False&#10; +  where False = &lt;method-wrapper '__eq__' of int object at 0x00007FFD9E547608&gt;(10)&#10; +    where &lt;method-wrapper '__eq__' of int object at 0x00007FFD9E547608&gt; = 20.__eq__">def test_assert_four():
        print("fail")
        a=20
        b=10
&gt;       assert a.__eq__(b),"A is not equal to B"
E       AssertionError: A is not equal to B
E       assert False
E        +  where False = &lt;method-wrapper '__eq__' of int object at 0x00007FFD9E547608&gt;(10)
E        +    where &lt;method-wrapper '__eq__' of int object at 0x00007FFD9E547608&gt; = 20.__eq__

xmlreport_test.py:24: AssertionError</failure></testcase></testsuite></testsuites>